<?php

namespace AppBundle\Repository;

/**
 * companyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class companyRepository extends \Doctrine\ORM\EntityRepository
{
}
